version: "3.8"
services:

  frontend:
    image: ozgurozturknet/phptodo:frontend
    ports:
      - 3000:80

  backend:
    image: ozgurozturknet/phptodo:backend
    ports:
      - 5000:80
    secrets:
      - mysql_password
    environment:
      HTTP_ORIGIN: http://34.245.58.97:3000

  database:
    image: ozgurozturknet/phptodo:database
    environment:
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_admin
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    secrets:
      - mysql_password
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
    depends_on:
      - database

networks:
  todo-network:
    driver: overlay

secrets:
  mysql_password:
    external: true

volumes:
  mysql-data:
    driver: local