name: Docker Image Release Pipeline

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    # docker-img-build-job:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v4
    #           name: Git Repo Checkout

    #         - name: Set up QEMU
    #           uses: docker/setup-qemu-action@v3
            
    #         - name: Set up Docker Buildx
    #           uses: docker/setup-buildx-action@v3

    #         - name: Login to Docker Hub
    #           uses: docker/login-action@v3
    #           with:
    #             username: ${{ secrets.DOCKERHUB_USERNAME }}
    #             password: ${{ secrets.DOCKERHUB_TOKEN }}

    #         - name: Build and push Frontend
    #           uses: docker/build-push-action@v5
    #           with:
    #             push: true
    #             tags: ozgurozturknet/phptodo:frontend
    #             file: ./Dockerfile.frontend

    #         - name: Build and push Backend
    #           uses: docker/build-push-action@v5
    #           with:
    #             push: true
    #             tags: ozgurozturknet/phptodo:backend
    #             file: ./Dockerfile.backend

    #         - name: Build and push Database
    #           uses: docker/build-push-action@v5
    #           with:
    #             push: true
    #             tags: ozgurozturknet/phptodo:database
    #             file: ./Dockerfile.database
    deploy-job:
      runs-on: ubuntu-latest
      # needs: docker-img-build-job
      steps:
        - uses: actions/checkout@v4
          name: Git Repo Checkout

        - name: Docker Stack Deploy
          uses: kitconcept/docker-stack-deploy@v1.0.1
          with:
            remote_host: ${{ secrets.REMOTE_HOST }}
            remote_user: ${{ secrets.REMOTE_USER }}
            remote_private_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
            stack_file: "docker-compose.yml"
            stack_name: "phptodo"