name: Docker Image Release Pipeline

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    docker-img-build-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Frontend
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: ozgurozturknet/phptodo:frontend
                file: ./Dockerfile.frontend

            - name: Build and push Backend
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: ozgurozturknet/phptodo:backend
                file: ./Dockerfile.backend

            - name: Build and push Database
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: ozgurozturknet/phptodo:database
                file: ./Dockerfile.database



            # - run: docker image build -t ozgurozturknet/phptodo-example:frontend -f ./Dockerfile.frontend
            # - run: docker image build -t ozgurozturknet/phptodo-example:backend -f ./Dockerfile.backend
            # - run: docker image build -t ozgurozturknet/phptodo-example:database -f ./Dockerfile.database
            # - run: docker login -u ozgurozturknet -p P@ssw0rd!
            # - run: docker push ozgurozturknet/phptodo-example:frontend
            # - run: docker push ozgurozturknet/phptodo-example:backend
            # - run: docker push ozgurozturknet/phptodo-example:database




        # image build et
        # docker'a login ol
        # docker push ile gönder