name: Ilk Test Pipeline

on:
    push:
        branches:
            - main
    workflow_dispatch:


jobs: 
    artifacts-deneme-job:
        runs-on: ubuntu-latest
        steps:
            - name: Hello
              run: echo "Hello World"
            
            - name: Dosya Oluşturma
              run: echo "Hello World" >> osman.txt 
            
            - name: Dosyayi Check Etme
              run: cat osman.txt

            - name: Artifact upload
              uses: actions/upload-artifact@v4
              with:
               name: Osman Abi'nin Raporu
               path: osman.txt


    artifacts-deneme2-job:
        needs: artifacts-deneme-job
        runs-on: ubuntu-latest
        steps:
            - name: Artifact Download
              uses: actions/download-artifact@v4
              with:
                name: Osman Abi'nin Raporu
                path: .
        
            - name: Test
              run: ls -al